name: Trigger auto deployment for httpapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'httpapiapp/**'
    - '.github/workflows/httpapi-AutoDeployTrigger-d837bfc4-0df8-4678-ad11-15f6d115ebe1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: hfacrname.azurecr.io
          username: ${{ secrets.HTTPAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.HTTPAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hfacrname.azurecr.io/httpapi:${{ github.sha }}
          file: ./httpapiapp/Dockerfile
          context: ./httpapiapp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HTTPAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n httpapi -g academo-rg --server hfacrname.azurecr.io --username  ${{ secrets.HTTPAPI_REGISTRY_USERNAME }} --password ${{ secrets.HTTPAPI_REGISTRY_PASSWORD }}
            az containerapp update -n httpapi -g academo-rg --image hfacrname.azurecr.io/httpapi:${{ github.sha }}
